### PR TITLE
Server/property resource api

### PR DESCRIPTION
**Pull request by BryceEvans**
- [x] - House API name changed to Property
- [x] - Property Tests written
- [x] - Property Tests Passing

@LBWright or @kybak  One quick Question: 

I added the task schema and the task tests. However, I don't see anywhere that signifies that '/api/tasks' nor '/api/properties' are set anywhere. From analyzing the code, I'm guessing I would want to add the following code to the router.js file, but didn't do it because I didn't want to touch a file in my branch that someone else might potentially mess with (thus creating a merge conflict).

```
import taskRouter from './task/task.router'
import propertyRouter from './property/property.router'

export const protectedRouter = app => {
  app.use(protect)
  app.use('/api/tasks', taskRouter)
}

export const protectedRouter = app => {
  app.use(protect)
  app.use('/api/properties', propertyRouter)
}
```

Does those need to be added to the index.js file?

I'd like this answered because I can't see anywhere that signifies the '/api/tasks' or '/api/properties' routes.

### CODE REVIEW

**Comment by LBWright** [comment]
@BryceEvans That's exactly right. Good inference. 
Go ahead and add it. I'll request changes so we know the PR's been looked at.

**Review by LBWright — CHANGES_REQUESTED** [review]
Go ahead and add these to the router.
You might have minor issues with the tests, however.

**Comment by BryceEvans** [comment]
Take a look in the router.js folder and let me know if what I did works or not.

**Review by LBWright — APPROVED** [review]
Looking good!

**Pull request merged**
